package com.rmtrev.projecteuler.questions;

/**
 * <b>Even Fibonacci numbers</b>
 * 
 * <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</p>
 * 
 * <p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
 * 
 * <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
 * 
 * @author rmt
 *
 */
public class Q002 implements IQuestion
{
	@Override
	public void Run(String[] args) throws Exception
	{
		int i1 = 1;
		int i2 = 2;
		int temp;
		
		long sum = 0;
		
		while(i1 < 4000000)
		{
			if(i1 % 2 == 0)
			{
				sum += i1;
			}
			
			temp = i1 + i2;
			i1 = i2;
			i2 = temp;
		}
		
		System.out.println(Long.toString(sum));
	}
}
